### ISSUE TITLE
battery icon doesn't work properly on sddm theme

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/artwork-maia#1]
A user just posted this issue in our [forum](https://forum.manjaro.org/index.php?topic=21295.msg190272#msg190272):

On the Maia-themed SDDM login and lock screens, the battery always displays 0% despite having a full charge.  If I change the lockscreen/login screen to Breeze, the battery icon works correctly.

<img src=http://i.imgur.com/6tcF2Nb.jpg</img>

**Comment by philmmanjaro** [comment]
We should check if ba890822b136a1c98312f6605172b53f503a78b1 already fixes this ...

**Comment by mcder3** [comment]
this error is not the artwork, but still'll check :P

**Comment by philmmanjaro** [comment]
@Kirek did some adjustments with ad6e7c91e77daddde40a26312e6647ed5aaf64ca

**Comment by Kirek** [comment]
Fixed with https://github.com/manjaro/artwork-maia/commit/ad6e7c91e77daddde40a26312e6647ed5aaf64ca
