### ISSUE TITLE
[plasma] Indication of minimized window in Icons-only Task Manager

### ISSUE THREAD

**Issue by elman22** [manjaro/artwork-maia#11]
I use Icons-only Task Manager and a lot of "Show A Launcher When Not Running". I have problem identifying minimized windows. They have no indicator and look exactly like not running (launcher only) applications. When I switch theme to Breeze, there is an indicator. So I guess it's problem with theme.

See attached image
Double Commander - running maximized in background
Octopi - running and minimized
KWrite - not running, Launcher only
System Settings - running in foreground

![image-1278](https://cloud.githubusercontent.com/assets/9151352/13522125/c68ac8d4-e1ed-11e5-8086-31630040029d.png)

Is there any way to make minimized applications identifiable?

Thanks, Elman

**Comment by Kirek** [comment]
I investigated a little and it seems the theme is missing some images, I managed to fix it:
![screenshot_20160305_043605](https://cloud.githubusercontent.com/assets/3207574/13545433/d52f9bd2-e28b-11e5-8816-c1b8159ec982.png)
They grey background is running and minimized.

**Comment by elman22** [comment]
Excellent, thanks a lot!
