### ISSUE TITLE
Icons for dark maia theme

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/artwork-maia#12]
Gtk3 apps look real nice with maia theme and dark theme enabled. However, maia icon theme is completely unusable with it because button icons become indistinguishable from their background. Breeze-icons has breeze-dark icon theme for this purpose and it works nicely. Since maia is mostly based on breeze-icons, would it be possible to port dark icons too? I would use it for bspwm edition, and it would also make maia more viable choice for any gtk3 based edition.

**Comment by oberon2007** [comment]
https://github.com/manjaro/artwork-maia/commit/1943363ca94ebc93829ebaaccf318b2a6d4a0021

**Comment by oberon2007** [comment]
**maia-icon-theme 0.6.0-2** now includes a dark version :)
