### ISSUE TITLE
Missing icons, SDDM-theme?

### ISSUE THREAD

**Issue by francoism90** [manjaro/artwork-maia#14]
Thanks for providing this wonderful theme! :D

A few suggestions:
- No icon for KeePassX 
- Other start-here for non-manjaro ([My recomendation](https://vdesign.kde.org/img/logowhite.png))
- Pictures-folder in Launcher used a different style (could be an issue at my end)

Many thanks. :)

**Comment by mcder3** [comment]
At the moment Maia is put on hold while the new artwork is finished.

**Comment by francoism90** [comment]
Hi @mcder3 

Could you give a bit more details about the new artwork?
Is this till for Maia?

Thanks :)

**Comment by mcder3** [comment]
@francoism90 It will be a clear theme and rely a little more breeze https://github.com/manjaro/artwork-andromeda

**Comment by francoism90** [comment]
@mcder3  Thanks for the link! What will happen with this repo? I really like this plasma-theme, would be great if this would still receive updates (icons/colors, etc. could be taken from Andromeda), although I understand maintaining more then one will be difficult.

Thanks. :)

**Comment by philmmanjaro** [comment]
**maia** is the default theme of **Manjaro 16.06**, so yes, updates will happen here still.

**Comment by francoism90** [comment]
@philmmanjaro That's great news. :+1:
