### ISSUE TITLE
Networkmanager Does not change or show vpn status

### ISSUE THREAD

**Issue by gizzmoguy** [manjaro/artwork-maia#15]
The network manager applet does not change when a vpn is connected. So you never know the status of your vpn whether connected or disconnected with a glans at the status bar. Icons usually changes to a lock.

**Comment by philmmanjaro** [comment]
@gizzmoguy: did you already tried a different theme to verify it is a **maia** issue.

**Comment by gizzmoguy** [comment]
Breeze Icons works perfectly fine i have attached screenshots
