### ISSUE TITLE
[Request] Battle.net icon

### ISSUE THREAD

**Issue by Strit** [manjaro/artwork-maia#19]
Hi team.

Love the new icon set, it's really fancy.

I'd like to request an icon for Battle.net.
I know it's not a Linux app, but it had an icon in the previous version of the Maia icons.

Feel free to say no, if it's too much hassle and you took it out because the icon pack got to bloated.

**Comment by mcder3** [comment]
You can share the app icon to review it

**Comment by Strit** [comment]
This one is a good representation of it:
[image](http://orig13.deviantart.net/7553/f/2013/231/2/9/battlenet_by_johnkict-d6ive6z.png)

**Comment by mcder3** [comment]
I will try to design that icon over the course of these days

**Comment by Strit** [comment]
Very nice. I appriciate it!

**Comment by Strit** [comment]
Since the set got "renamed/forked" into artwork-breath instead, I still haven't seen any battle.net icon in it.
Did it get dropped? To much work?

Anyway I'll close it here, since it's not related to artwork-maia anymore anyway.
