### ISSUE TITLE
Icons on KDE Taskbar are very small.

### ISSUE THREAD

**Issue by Shylon** [manjaro/artwork-maia#20]
Hi, I use Manjaro and using The default Breath Theme for KDE, (default Task Bar Size ), but when I switch to Maia Theme, all Icons on taskbar are very smaller comparing to Breath, both pinned and openned apps.
It would be nice to see bigger Icons similar to Breath Theme.
Thanks for such a nice Theme :).

**Comment by mcder3** [comment]
Maia for KDE is no longer supported.

**Comment by Shylon** [comment]
Oh, OK, Thank you.
