### ISSUE TITLE
Provid How-to for installing artwork for another KDE distribution

### ISSUE THREAD

**Issue by tonny-sofijan** [manjaro/artwork-maia#21]
Dear Manjaro dev,

Could you provide how-to for people that want to use your artwork for another KDE distribution? I'm using archlinux KDE, and very interested with your artwork. I want to use the artwork without having to reinstall. Or could you post your artwork to kde server so anybody else can just grab it from systemsettings? Thanks!

**Comment by oberon2007** [comment]
All the PKGBUILDs can be found in the [community-repo](https://github.com/manjaro/packages-community)

**Comment by tonny-sofijan** [comment]
Many thanks! have it installed. :+1:

**Comment by oberon2007** [comment]
great! :)
