### ISSUE TITLE
[xfce] emblems/symbolic minimum size should be 16

### ISSUE THREAD

**Issue by cadecairos** [manjaro/artwork-maia#3]
It's set to 32, which causes massive menu icons to be displayed in apps like Pamac

**Comment by mcder3** [comment]
You can send a screenshot to verify the error.

**Comment by cadecairos** [comment]
![pamac](https://cloud.githubusercontent.com/assets/438003/7301221/51f56c9a-e9af-11e4-99a7-533faea8c9f1.png)

**Comment by cadecairos** [comment]
and here it is when I hotfix the value to 16:

![pamac2](https://cloud.githubusercontent.com/assets/438003/7301254/817936e0-e9af-11e4-90ae-ae3be5ebd476.png)

**Comment by mcder3** [comment]
Thanks for reporting the error
