### ISSUE TITLE
how to install?can you tell me?

### ISSUE THREAD

**Issue by wujianye3** [manjaro/artwork-maia#4]
There is less information in readme.md

**Comment by mcder3** [comment]
What do you want to install? since in this repository there are tools for different environments.

**Comment by philmmanjaro** [comment]
You can use our [PKGBUILD](https://github.com/manjaro/packages-community/blob/master/artwork-maia/PKGBUILD) to install it on your system. Depends what you want to install here ...

**Comment by wujianye3** [comment]
thanks!

**Comment by wujianye3** [comment]
I have installed the theme after scaning "PKGBUILD".
Thank you, very much!

**Comment by nanotime** [comment]
Hm, if i want to install it on kubuntu? Im watching various cmake files :D
