### ISSUE TITLE
Cannot assign to non-existent property \"typeText\"\n"

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/artwork-maia#5]
Hi David,

can you take a look at [this](https://forum.manjaro.org/index.php?topic=25485.msg218049#msg218049):

I have an issue with krunner as well. The process is running according to system info but the program cannot be launched, i.e. the standard shortcut alt F2 does not work.
I killed the process and got the following error message when launching krunner in konsole:
```
"file:///usr/share/plasma/look-and-feel/org.kde.maia.desktop/contents/runcommand/RunCommand.qml"
"Error loading QML file.\n167: Cannot assign to non-existent property \"typeText\"\n"
```

**Comment by mcder3** [comment]
I think that's the code that implemented Kirek to work on Plasma 5.4

I can run without any problem krunner in Manjaro KDE Next

**Comment by Kirek** [comment]
I will take a look at it.

**Comment by Kirek** [comment]
Fixed in https://github.com/manjaro/artwork-maia/commit/088e984638285a54d77b0d502f8775cf69bf1944 I'm going to push it to all branches.

**Comment by philmmanjaro** [comment]
Ok, I tested it also only in Plasma 5.4.
