### ISSUE TITLE
"Save Session" icon in Kickoff

### ISSUE THREAD

**Issue by cubanpit** [manjaro/artwork-maia#6]
KDE Plasma 5 (Manjaro)
The icon for "Save Session" option in the menu (KickOff I think it's the official name) is dark, so quite invisible.
P.S. The theme is great.
![kstempscreenshot](https://cloud.githubusercontent.com/assets/13075429/9786441/5340e0ba-57ba-11e5-938e-8a531e1a2953.png)

**Comment by mcder3** [comment]
f the icon is modified many applications leave affected.

**Comment by mcder3** [comment]
What Maia version are you using?

**Comment by cubanpit** [comment]
maia-icon-theme 0.5.2-1 from Manjaro testing repository.
I understand only now that it's probably the same icon for the "Save" button in many applications; so it's probably better to leave it like that.
