### ISSUE TITLE
[KDE] Default theme fonts don't support cyrillics

### ISSUE THREAD

**Issue by mikhailnov** [manjaro/artwork-maia#7]
The default font of the Maia KDE theme seems to not support cyrillic characters. 
![deepinscreenshot20151111184321](https://cloud.githubusercontent.com/assets/15802528/11095141/985ceca0-88a4-11e5-8c44-58ee25078965.png)
![deepinscreenshot20151111184249](https://cloud.githubusercontent.com/assets/15802528/11095142/98625262-88a4-11e5-93fd-91e470b3bf91.png)
Please see the differences in the screens.

**Comment by Kirek** [comment]
First of all the Maia theme has nothing to do with the fonts used.

That being said we do use the oxygen font in the KDE edition that seems to not support Cyrillic characters, and it's a known problem https://bugs.kde.org/show_bug.cgi?id=344989

Maybe we will use another font by default in the 15.12 release.

**Comment by mikhailnov** [comment]
Thank you, I see.

**Comment by mikhailnov** [comment]
I changes Oxygen Sans to Open Sans and that's OK, it's similar to Oxygen Sans (but Oxygen is a bit better to my mind) and dupports cyrillic symbols.

**Comment by philmmanjaro** [comment]
So we can close this?

**Comment by mikhailnov** [comment]
Maybe, but the bug with cyrillic symbols will remain. 0:19, 12 ноября 2015 г., "Philip Müller" <notifications@github.com>:So we can close this? —Reply to this email directly or view it on GitHub.     Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by philmmanjaro** [comment]
Well, it is already an [upstream bug](https://bugs.kde.org/show_bug.cgi?id=344989). Nothing we can do about it at this level.

**Comment by Kirek** [comment]
In the Manjaro KDE 15.12 we will be using Noto Fonts, so this shouldn't be an issue anymore.
