### ISSUE TITLE
[plasma] Dark icons hard to see

### ISSUE THREAD

**Issue by adamsts** [manjaro/artwork-maia#8]
I noticed that the icons on the main panel appear normal when the panel is larger however when the panel height is reduced certain icons change to a darker version which then blend in with the panel background.  In particular the "show desktop" as well as some of the tray icons exhibit this behavior.  I am running a fresh (with all updates) install of Manjaro Plasma 15.12.

Larger icons:
![screenshot_20160102_193057](https://cloud.githubusercontent.com/assets/6218377/12076756/b5256b62-b187-11e5-914a-a1f958da09dd.png)

Reduced size:
![screenshot_20160102_193035](https://cloud.githubusercontent.com/assets/6218377/12076757/c180fb92-b187-11e5-9ac9-1340ba9a5514.png)

**Comment by oberon2007** [comment]
**maia-icon-theme 0.6.0-2** now includes a dark version.
